# Generated by Django 3.2a1 on 2021-02-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
